name: sankey_flutter
description: About Flutter package for Sankey diagrams (flow charts).
version: 0.0.2
homepage: https://github.com/Jason-Gregoire/sankey_flutter
repository: https://github.com/Jason-Gregoire/sankey_flutter
issue_tracker: https://github.com/Jason-Gregoire/sankey_flutter/issues

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
